import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { api, download, hasRole } from '../api';
import { Badge, Button, Card, ErrorBox, Field, fmt, Input, Page, Select, Table, useMe } from '../ui';

type Row = Record<string, unknown>;

const OUTCOMES = ['reached_converted', 'reached_not_interested', 'reached_callback', 'no_answer', 'wrong_number', 'do_not_call'];

export function CallList() {
  const me = useMe();
  const qc = useQueryClient();
  const [status, setStatus] = useState('');
  const [reason, setReason] = useState('');
  const params = new URLSearchParams({ ...(status ? { status } : {}), ...(reason ? { reason } : {}) });
  const q = useQuery({ queryKey: ['calls', params.toString()], queryFn: () => api<{ total: number; items: Row[] }>(`/admin/call-tasks?${params}`) });
  const [error, setError] = useState<unknown>(null);

  const update = async (id: string, body: Record<string, unknown>) => {
    setError(null);
    try {
      await api(`/admin/call-tasks/${id}`, { method: 'PUT', body });
      await qc.invalidateQueries({ queryKey: ['calls'] });
    } catch (e) {
      setError(e);
    }
  };

  return (
    <Page
      title="Call list"
      subtitle="Generated by journeys and the CRM — never by a manual export. Calls run 10:00–20:00, Sunday to Thursday, max 2 per client per quarter."
      actions={hasRole(me.data, 'callcentre', 'crm') ? <Button onClick={() => download('/admin/call-tasks/export.csv', 'call-list.csv')}>Export for dialler (CSV)</Button> : undefined}
    >
      <Card>
        <div className="mb-4 grid gap-3 sm:grid-cols-3">
          <Select value={status} onChange={setStatus} options={['open', 'in_progress', 'done', 'cancelled']} placeholder="Open & in progress" />
          <Select value={reason} onChange={setReason} options={['activation_help', 'manual_kyc', 'recurring_xsell', 'former_instalment', 'winback', 'large_ticket', 'complaint_recovery']} placeholder="All reasons" />
          <p className="self-center text-sm text-stone-500">{q.data ? `${fmt.num(q.data.total)} tasks` : ''}</p>
        </div>
        <ErrorBox error={error ?? q.error} />
        <Table
          rows={q.data?.items}
          columns={[
            { key: 'priority', label: 'P' },
            { key: 'dueAt', label: 'Due', render: (r) => fmt.date(r.dueAt as string) },
            { key: 'reason', label: 'Reason' },
            {
              key: 'client',
              label: 'Client',
              render: (r) => {
                const c = r.client as Row;
                return (
                  <Link className="text-gold-700 hover:underline" to={`/clients/${String(c.externalId)}`}>
                    {String(c.fullName ?? c.externalId)}
                  </Link>
                );
              },
            },
            { key: 'phone', label: 'Phone', render: (r) => String((r.client as Row).phone ?? '—') },
            { key: 'tier', label: 'Tier / stage', render: (r) => `${String((r.client as Row).valueTier)} · ${String((r.client as Row).lifecycleStage)}` },
            { key: 'status', label: 'Status', render: (r) => <Badge>{String(r.status)}</Badge> },
            {
              key: 'outcome',
              label: 'Outcome',
              render: (r) => (
                <div className="w-48">
                  <Select value={String(r.outcome ?? '')} onChange={(v) => update(String(r.id), { outcome: v, status: v === 'reached_callback' || v === 'no_answer' ? 'in_progress' : 'done' })} options={OUTCOMES} placeholder="Log outcome…" />
                </div>
              ),
            },
          ]}
        />
      </Card>
    </Page>
  );
}

export function Suppression() {
  const qc = useQueryClient();
  const [search, setSearch] = useState('');
  const q = useQuery({ queryKey: ['suppressions', search], queryFn: () => api<{ total: number; items: Row[] }>(`/admin/suppressions?${new URLSearchParams(search ? { q: search } : {})}`) });
  const [form, setForm] = useState({ channel: 'email', value: '', scope: 'marketing', reason: 'manual', note: '' });
  const [error, setError] = useState<unknown>(null);

  return (
    <Page title="Suppression list" subtitle="One authoritative do-not-contact list consumed by every channel. Opt-outs apply immediately. Scope “all” (invalid destination) also blocks transactional messages.">
      <Card title="Add">
        <div className="grid gap-3 sm:grid-cols-6">
          <Field label="Channel"><Select value={form.channel} onChange={(v) => setForm({ ...form, channel: v })} options={['email', 'sms', 'push', 'whatsapp', 'call', 'all']} /></Field>
          <Field label="Value" hint="Email, phone or client ID"><Input value={form.value} onChange={(e) => setForm({ ...form, value: e.target.value })} /></Field>
          <Field label="Scope"><Select value={form.scope} onChange={(v) => setForm({ ...form, scope: v })} options={['marketing', 'all']} /></Field>
          <Field label="Reason"><Select value={form.reason} onChange={(v) => setForm({ ...form, reason: v })} options={['manual', 'complaint', 'unsubscribe', 'legal_request', 'do_not_call']} /></Field>
          <Field label="Note"><Input value={form.note} onChange={(e) => setForm({ ...form, note: e.target.value })} /></Field>
          <div className="self-end">
            <Button variant="primary" onClick={async () => {
              setError(null);
              try {
                await api('/admin/suppressions', { body: form });
                setForm({ ...form, value: '', note: '' });
                await qc.invalidateQueries({ queryKey: ['suppressions'] });
              } catch (e) {
                setError(e);
              }
            }}>Suppress</Button>
          </div>
        </div>
        <ErrorBox error={error} />
      </Card>
      <Card>
        <div className="mb-3 max-w-sm"><Input placeholder="Search value" value={search} onChange={(e) => setSearch(e.target.value)} /></div>
        <Table
          rows={q.data?.items}
          columns={[
            { key: 'createdAt', label: 'Added', render: (r) => fmt.date(r.createdAt as string) },
            { key: 'channel', label: 'Channel' },
            { key: 'value', label: 'Value' },
            { key: 'scope', label: 'Scope', render: (r) => <Badge tone={r.scope === 'all' ? 'failed' : 'draft'}>{String(r.scope)}</Badge> },
            { key: 'reason', label: 'Reason' },
            { key: 'source', label: 'Source' },
            { key: 'x', label: '', render: (r) => <Button small variant="ghost" onClick={async () => { await api(`/admin/suppressions/${String(r.id)}`, { method: 'DELETE' }); await qc.invalidateQueries({ queryKey: ['suppressions'] }); }}>Remove</Button> },
          ]}
        />
      </Card>
    </Page>
  );
}
